### PR TITLE
Remove favorites through endpoint for user

### LINKED ISSUE #16: Create DELETE /api/v1/favorites Endpoint
- [ ] Jest Testing
- [ ] Swagger.io endpoint AND documentation
- [x] API key must be sent If no API key or an incorrect key is provided return 401 (Unauthorized)
- [x] Response has 204 status and no body
- [x] User is able to delete all favorites

**Endpoint Format**

Request:
```
DELETE /api/v1/favorites
Content-Type: application/json
Accept: application/json

body:

{
  "location": "Denver, CO",
  "api_key": "jgn983hy48thw9begh98h4539h4"
}
```

Response:
```
status: 204
```

### PR DESCRIPTION
**Pull request by blake-enyart**
- [] Check this if the PR has been approved by the team to be a quick patch and the rest of this form will not be filled out

# Test Coverage Percentage (Model/Feature):
- Need to integrate in the future

# What functionality does this accomplish?
* Creates delete endpoint that allows a user to remove a favorite if they have the appropriate api key
* Uses the `User.removeLocations(location)` to remove a specific association through the joins table, but still maintains the original location as the default for the `onDelete` attr in the migration is to `SET NULL` rather than `cascade` which would result in the removal of the associated location record
* Allows user to delete ALL favorites

# What did you struggle on to complete?
* Nothing in particular

# Implements/Fixes:
* description
closes #16 

# Testing Changes
- [x] No Tests have been changed
- [] Some Tests have been changed
- [] All of the Tests have been changed(Please describe what in the world happened)

# Checklist:

- [x] My code has no unused/commented out code
- [x] I have reviewed my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have fully tested my code

# Please include an emoji of how you feel about this branch:
# 👏 

@jalena-penaligon: Can you think of other ways I might be able to better organize this code for scalability? I'm thinking about the controller in particular since it is so large, but I can't come up with anything offhand.

### CODE REVIEW

File: controllers/api/v1/favorites_controller.js [hunk 1]
```diff
@@ -48,10 +48,28 @@ async function index(req, res) {
...
+    let [city, state] = req.body.location.split(',');
+    state = state.trim().toLowerCase();
+    city = city.trim().toLowerCase();
+
+    let location = await Location.findOne({where: {city: city, state: state}});
+    await user.removeLocations(location);
+    res.status(204).send();
+  } else {
+    res.status(401).send({message: `Invalid credentials.`});
   }
```
Comment (jalena-penaligon) [inline controllers/api/v1/favorites_controller.js]: I think this is about as trim as you can get to complete the required functionality :) One thing I did see, I'm curious about the  || null option when searching for a User. Is there something specific you're hoping to catch with that or operator? If not, that syntax is not necessary to achieve the desired result, and I'm not sure if it could open it up for null api_key submissions?

Comment (blake-enyart) [reply controllers/api/v1/favorites_controller.js]: Great question! So I was running into issues where is `undefined` is passed into the sequelize method it gave an error so I added the or operator to change the value to null in the case where the API key is not given. Where you able to get it to work with no API key passed in?
